-- Generated by the database client, not guaranteed complete.
CREATE TABLE cuentas(
    "id" SERIAL NOT NULL,
    "saldo" numeric,
    PRIMARY KEY(id),
    CONSTRAINT cuentas_saldo_check CHECK ((saldo >= (0)::numeric))
);